# Generated by Django 5.1.2 on 2024-11-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
