# Generated by Django 5.1.2 on 2024-11-07 20:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('MYS', 'Mystery'), ('SCI', 'Science Fiction'), ('FAN', 'Fantasy')], max_length=3)),
                ('description', models.TextField()),
                ('languages', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('AR', 'Arabic'), ('SP', 'Spanish'), ('IT', 'Italian'), ('CH', 'Chinese')], max_length=2)),
                ('publication_date', models.DateField()),
                ('content', models.FileField(blank=True, null=True, upload_to='books/content_pdfs/')),
                ('audio_version', models.FileField(blank=True, null=True, upload_to='books/audio_versions/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/cover_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_stars', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('audio_length', models.DurationField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=core.models.image_upload),
        ),
    ]
