# Generated by Django 5.1.2 on 2024-11-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_book_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='priceDZD',
        ),
        migrations.AddField(
            model_name='book',
            name='priceUSD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
