# Generated by Django 5.1.2 on 2024-11-08 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_price_book_pricedzd_book_priceusd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Sci-fi', 'Science Fiction'), ('Fantasy', 'Fantasy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('AR', 'Arabic'), ('SP', 'Spanish'), ('IT', 'Italian'), ('CH', 'Chinese')], max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('stars', models.PositiveSmallIntegerField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
