# Generated by Django 5.1.2 on 2024-11-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recent_books',
            field=models.ManyToManyField(blank=True, related_name='recently_viewed_by_profiles', to='core.book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_books',
            field=models.ManyToManyField(blank=True, related_name='saved_by_profiles', to='core.book'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_audio', models.BooleanField(default=False)),
                ('purchased_pdf', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='purchased_books',
            field=models.ManyToManyField(blank=True, related_name='purchased_by_profiles', through='core.Purchase', to='core.book'),
        ),
    ]
