# Generated by Django 5.1.2 on 2024-11-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_recent_books_profile_saved_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recent_books',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_books',
        ),
    ]
